AllCops:
  Include:
    - '**/Rakefile'
  Exclude:
    - '.gems/**/*'
    - 'vendor/**/*'

StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

Metrics/MethodLength:
  Max: 15

TrailingComma:
  EnforcedStyleForMultiline: comma
